version: '3.8'

services:
  app:
    build: .
    ports:
      - "${PORT:-8080}:8080"
    environment:
      POSTGRES_URI: ${POSTGRES_URI}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      REDIS_URI: ${REDIS_URI}
      JWT_SECRET: ${JWT_SECRET}
      JWT_ACCESS_EXPIRE: ${JWT_ACCESS_EXPIRE}
      JWT_REFRESH_EXPIRE: ${JWT_REFRESH_EXPIRE}