spring:
  application:
    name: "chirp-chirp"

  datasource:
    url: ${POSTGRES_URI}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver

  redis:
    uri: ${REDIS_URI}

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration
    baseline-version: 0

  jwt:
    issuer: "chirp-chirp"
    secret-key: ${JWT_SECRET}
    access-token-expiration-minute: ${JWT_ACCESS_EXPIRE}
    refresh-token-expiration-minute: ${JWT_REFRESH_EXPIRE}

logging:
  level:
    root: info
    viet.io.chirpchirp: debug

server:
    port: ${PORT}