spring:
  application:
    name: "chirp-chirp"

  datasource:
    url: jdbc:postgresql://localhost:5432/chirp-chirp
    username: viet
    password: 123
    driver-class-name: org.postgresql.Driver

  redis:
    uri: redis://localhost:6379

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration
    baseline-version: 0

  jwt:
    issuer: "chirp-chirp"
    secret-key: "secret"
    access-token-expiration-minute: 60
    refresh-token-expiration-minute: 1440

logging:
  level:
    root: info
    viet.io.chirpchirp: debug